### ISSUE TITLE
1 Loại tiêu đề khác

### ISSUE THREAD

**Issue by kourain** [h3x4n1um/AoV-Zstd#1]
Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác
![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)

**Comment by Conmeno3571** [comment]
> Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác ![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)
Đây là file change.xml mà t gửi m à :v ?

**Comment by innocentvoice** [comment]
> Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác ![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)

What's the name of the file, and where did you got it?

**Comment by h3x4n1um** [comment]
> > Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác ![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)
> 
> What's the name of the file, and where did you got it?

I don't think he likely to answer your question based on the fact that if he's willing to share then he would upload the actual file instead of the screenshot

**Comment by innocentvoice** [comment]
> > > Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác ![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)
> > 
> > 
> > What's the name of the file, and where did you got it?
> 
> I don't think he likely to answer your question based on the fact that if he's willing to share then he would upload the actual file instead of the screenshot

hmm...you are correct, but it seems it's still zstandard i think. The new version still keep the same key. 
p/s: Actually i use google translate to translate what he said so i'm not sure what he mean

**Comment by innocentvoice** [comment]
anyways do you use discord or anything, i would like to send a friend request

**Comment by kourain** [comment]
I don't remember what and where that file is
but now i see another similar file
[ResComponentMeshReplace.txt](https://github.com/h3x4n1um/AoV-Zstd/files/9059805/ResComponentMeshReplace.txt)
Path: .\1.46.1\\Databin\Client\Character\


> > > > Chào bạn, ở đây tôi có 1 file cũng từ AOV nhưng có 1 tiêu đề khác ![image](https://user-images.githubusercontent.com/85356599/175842058-a0a7f790-c253-4c37-892b-51f218f623a5.png)
> > > 
> > > 
> > > What's the name of the file, and where did you got it?
> > 
> > 
> > I don't think he likely to answer your question based on the fact that if he's willing to share then he would upload the actual file instead of the screenshot
> 
> hmm...you are correct, but it seems it's still zstandard i think. The new version still keep the same key. p/s: Actually i use google translate to translate what he said so i'm not sure what he mean

**Comment by kourain** [comment]
> anyways do you use discord or anything, i would like to send a friend request

discord yes
Kourain#1517

**Comment by innocentvoice** [comment]
> anyways do you use discord or anything, i would like to send a friend request

*i also mean this to h3x4n1um*

**Comment by WollieWoltaz** [comment]
What should I do after compression? 
It stated that i have to "recheck output"  but what does that mean?
Also... is it possible to open the compressed files with Assetstudio?

**Comment by innocentvoice** [comment]
> What should I do after compression? It stated that i have to "recheck output" but what does that mean? Also... is it possible to open the compressed files with Assetstudio?

it will be saved as .compressed, then you can rename it to .xml , and I don't think you can, it's zstd

**Comment by WollieWoltaz** [comment]
And what is the purpose of renaming it to an .xml file? 
Sorry to ask.. i'm a bit confused about the benefits of this tool?

I thought... you guys finally figured out how to get the models/animations from AoV after there huge update
but this tool is not for that right?

Thanks for reply,

**Comment by innocentvoice** [comment]
> And what is the purpose of renaming it to an .xml file? Sorry to ask.. i'm a bit confused about the benefits of this tool?
- This tool can decompress AOV files, you can use this tool for skins modding, or do other stuff. And to use the file after you compress/decompress. Rename it to xml (e.g A1.xml) or it original file format (.bytes, etc...)
> I thought... you guys finally figured out how to get the models/animations from AoV after there huge update but this tool is not for that right?
- this tool can decompress most of the files in aov
> Thanks for reply,
- No problem!

**Comment by WollieWoltaz** [comment]
I see. That makes sence.
Do you know of a tool or script that can decrypt the .unity asset files so they'll be able to load up into AssetStudio?

**Comment by innocentvoice** [comment]
> I see. That makes sence. Do you know of a tool or script that can decrypt the .unity asset files so they'll be able to load up into AssetStudio?

In fact, assetbundle file of aov can be use in assetstudio

**Comment by WollieWoltaz** [comment]
Yeah older versions do work, but the latest version not. Assetstudio throws out an error.
But please... eleborate more.. I'm curious how i could achieve that.

**Comment by WollieWoltaz** [comment]
??
